/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author USUARIO
 */
public class Tablero5x5 extends javax.swing.JFrame {

    /**
     * Creates new form Tablero5x5
     */
    
    private JLabel[][] casillas;
    
    public Tablero5x5() {
        initComponents();
        this.setLocationRelativeTo(null);
        casillas = new JLabel[5][5];
        setCasi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        casilla1 = new javax.swing.JLabel();
        casilla6 = new javax.swing.JLabel();
        casilla11 = new javax.swing.JLabel();
        casilla2 = new javax.swing.JLabel();
        casilla7 = new javax.swing.JLabel();
        casilla12 = new javax.swing.JLabel();
        casilla8 = new javax.swing.JLabel();
        casilla13 = new javax.swing.JLabel();
        casilla3 = new javax.swing.JLabel();
        casilla4 = new javax.swing.JLabel();
        casilla9 = new javax.swing.JLabel();
        casilla14 = new javax.swing.JLabel();
        casilla16 = new javax.swing.JLabel();
        casilla17 = new javax.swing.JLabel();
        casilla18 = new javax.swing.JLabel();
        casilla19 = new javax.swing.JLabel();
        casilla5 = new javax.swing.JLabel();
        casilla10 = new javax.swing.JLabel();
        casilla15 = new javax.swing.JLabel();
        casilla20 = new javax.swing.JLabel();
        casilla21 = new javax.swing.JLabel();
        casilla22 = new javax.swing.JLabel();
        casilla23 = new javax.swing.JLabel();
        casilla24 = new javax.swing.JLabel();
        casilla25 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblJugador1 = new javax.swing.JLabel();
        lblJugador2 = new javax.swing.JLabel();
        lblPuntos1 = new javax.swing.JLabel();
        lblPuntos2 = new javax.swing.JLabel();
        btnReiniciar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 5));

        casilla1.setBackground(new java.awt.Color(255, 255, 255));
        casilla1.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        casilla1.setForeground(new java.awt.Color(0, 0, 0));
        casilla1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        casilla1.setOpaque(true);

        casilla6.setBackground(new java.awt.Color(255, 255, 255));
        casilla6.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        casilla6.setForeground(new java.awt.Color(0, 0, 0));
        casilla6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        casilla6.setOpaque(true);

        casilla11.setBackground(new java.awt.Color(255, 255, 255));
        casilla11.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        casilla11.setForeground(new java.awt.Color(0, 0, 0));
        casilla11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        casilla11.setOpaque(true);

        casilla2.setBackground(new java.awt.Color(255, 255, 255));
        casilla2.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        casilla2.setForeground(new java.awt.Color(0, 0, 0));
        casilla2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        casilla2.setOpaque(true);

        casilla7.setBackground(new java.awt.Color(255, 255, 255));
        casilla7.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        casilla7.setForeground(new java.awt.Color(0, 0, 0));
        casilla7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        casilla7.setOpaque(true);

        casilla12.setBackground(new java.awt.Color(255, 255, 255));
        casilla12.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        casilla12.setForeground(new java.awt.Color(0, 0, 0));
        casilla12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        casilla12.setOpaque(true);

        casilla8.setBackground(new java.awt.Color(255, 255, 255));
        casilla8.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        casilla8.setForeground(new java.awt.Color(0, 0, 0));
        casilla8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        casilla8.setOpaque(true);

        casilla13.setBackground(new java.awt.Color(255, 255, 255));
        casilla13.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        casilla13.setForeground(new java.awt.Color(0, 0, 0));
        casilla13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        casilla13.setOpaque(true);

        casilla3.setBackground(new java.awt.Color(255, 255, 255));
        casilla3.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        casilla3.setForeground(new java.awt.Color(0, 0, 0));
        casilla3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        casilla3.setOpaque(true);

        casilla4.setBackground(new java.awt.Color(255, 255, 255));
        casilla4.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        casilla4.setForeground(new java.awt.Color(0, 0, 0));
        casilla4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        casilla4.setOpaque(true);

        casilla9.setBackground(new java.awt.Color(255, 255, 255));
        casilla9.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        casilla9.setForeground(new java.awt.Color(0, 0, 0));
        casilla9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        casilla9.setOpaque(true);

        casilla14.setBackground(new java.awt.Color(255, 255, 255));
        casilla14.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        casilla14.setForeground(new java.awt.Color(0, 0, 0));
        casilla14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        casilla14.setOpaque(true);

        casilla16.setBackground(new java.awt.Color(255, 255, 255));
        casilla16.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        casilla16.setForeground(new java.awt.Color(0, 0, 0));
        casilla16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        casilla16.setOpaque(true);

        casilla17.setBackground(new java.awt.Color(255, 255, 255));
        casilla17.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        casilla17.setForeground(new java.awt.Color(0, 0, 0));
        casilla17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        casilla17.setOpaque(true);

        casilla18.setBackground(new java.awt.Color(255, 255, 255));
        casilla18.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        casilla18.setForeground(new java.awt.Color(0, 0, 0));
        casilla18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        casilla18.setOpaque(true);

        casilla19.setBackground(new java.awt.Color(255, 255, 255));
        casilla19.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        casilla19.setForeground(new java.awt.Color(0, 0, 0));
        casilla19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        casilla19.setOpaque(true);

        casilla5.setBackground(new java.awt.Color(255, 255, 255));
        casilla5.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        casilla5.setForeground(new java.awt.Color(0, 0, 0));
        casilla5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        casilla5.setOpaque(true);

        casilla10.setBackground(new java.awt.Color(255, 255, 255));
        casilla10.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        casilla10.setForeground(new java.awt.Color(0, 0, 0));
        casilla10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        casilla10.setOpaque(true);

        casilla15.setBackground(new java.awt.Color(255, 255, 255));
        casilla15.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        casilla15.setForeground(new java.awt.Color(0, 0, 0));
        casilla15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        casilla15.setOpaque(true);

        casilla20.setBackground(new java.awt.Color(255, 255, 255));
        casilla20.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        casilla20.setForeground(new java.awt.Color(0, 0, 0));
        casilla20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        casilla20.setOpaque(true);

        casilla21.setBackground(new java.awt.Color(255, 255, 255));
        casilla21.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        casilla21.setForeground(new java.awt.Color(0, 0, 0));
        casilla21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        casilla21.setOpaque(true);

        casilla22.setBackground(new java.awt.Color(255, 255, 255));
        casilla22.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        casilla22.setForeground(new java.awt.Color(0, 0, 0));
        casilla22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        casilla22.setOpaque(true);

        casilla23.setBackground(new java.awt.Color(255, 255, 255));
        casilla23.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        casilla23.setForeground(new java.awt.Color(0, 0, 0));
        casilla23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        casilla23.setOpaque(true);

        casilla24.setBackground(new java.awt.Color(255, 255, 255));
        casilla24.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        casilla24.setForeground(new java.awt.Color(0, 0, 0));
        casilla24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        casilla24.setOpaque(true);

        casilla25.setBackground(new java.awt.Color(255, 255, 255));
        casilla25.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        casilla25.setForeground(new java.awt.Color(0, 0, 0));
        casilla25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        casilla25.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(casilla21, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla16, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(casilla1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(casilla6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(casilla11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(casilla12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla17, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(casilla13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla18, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(casilla19, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(casilla5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla15, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla20, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(casilla22, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(casilla23, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(casilla24, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(casilla25, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(casilla4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(casilla2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(casilla7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(casilla3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(casilla8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(casilla1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(casilla6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(casilla5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(casilla10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(casilla13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla15, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(casilla16, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla17, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla18, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla19, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla20, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(casilla21, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla22, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla23, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla24, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla25, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 5));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Puntaje");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel1.setOpaque(true);

        lblJugador1.setBackground(new java.awt.Color(255, 255, 255));
        lblJugador1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lblJugador1.setForeground(new java.awt.Color(0, 0, 0));
        lblJugador1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblJugador1.setOpaque(true);

        lblJugador2.setBackground(new java.awt.Color(255, 255, 255));
        lblJugador2.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lblJugador2.setForeground(new java.awt.Color(0, 0, 0));
        lblJugador2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblJugador2.setOpaque(true);

        lblPuntos1.setBackground(new java.awt.Color(255, 255, 255));
        lblPuntos1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lblPuntos1.setForeground(new java.awt.Color(0, 0, 0));
        lblPuntos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPuntos1.setText("0");
        lblPuntos1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblPuntos1.setOpaque(true);

        lblPuntos2.setBackground(new java.awt.Color(255, 255, 255));
        lblPuntos2.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lblPuntos2.setForeground(new java.awt.Color(0, 0, 0));
        lblPuntos2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPuntos2.setText("0");
        lblPuntos2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblPuntos2.setOpaque(true);

        btnReiniciar.setBackground(new java.awt.Color(255, 102, 102));
        btnReiniciar.setForeground(new java.awt.Color(0, 0, 0));
        btnReiniciar.setText("Reinciar partida");

        btnSalir.setBackground(new java.awt.Color(255, 102, 102));
        btnSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPuntos2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPuntos1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnReiniciar)
                        .addGap(41, 41, 41)
                        .addComponent(btnSalir)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPuntos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPuntos2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReiniciar)
                    .addComponent(btnSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero5x5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero5x5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero5x5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero5x5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Modelo5x5 modelote = new Modelo5x5();
                Tablero5x5 tablerote = new Tablero5x5();
                Tablero_5x5 tab = new Tablero_5x5(tablerote, modelote);
                tablerote.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel casilla1;
    private javax.swing.JLabel casilla10;
    private javax.swing.JLabel casilla11;
    private javax.swing.JLabel casilla12;
    private javax.swing.JLabel casilla13;
    private javax.swing.JLabel casilla14;
    private javax.swing.JLabel casilla15;
    private javax.swing.JLabel casilla16;
    private javax.swing.JLabel casilla17;
    private javax.swing.JLabel casilla18;
    private javax.swing.JLabel casilla19;
    private javax.swing.JLabel casilla2;
    private javax.swing.JLabel casilla20;
    private javax.swing.JLabel casilla21;
    private javax.swing.JLabel casilla22;
    private javax.swing.JLabel casilla23;
    private javax.swing.JLabel casilla24;
    private javax.swing.JLabel casilla25;
    private javax.swing.JLabel casilla3;
    private javax.swing.JLabel casilla4;
    private javax.swing.JLabel casilla5;
    private javax.swing.JLabel casilla6;
    private javax.swing.JLabel casilla7;
    private javax.swing.JLabel casilla8;
    private javax.swing.JLabel casilla9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblJugador1;
    private javax.swing.JLabel lblJugador2;
    private javax.swing.JLabel lblPuntos1;
    private javax.swing.JLabel lblPuntos2;
    // End of variables declaration//GEN-END:variables

    private void setCasi() {
      casillas[0][0] = casilla1;
      casillas[0][1] = casilla2;
      casillas[0][2] = casilla3;
      casillas[0][3] = casilla4;
      casillas[0][4] = casilla5;
      casillas[1][0] = casilla6;
      casillas[1][1] = casilla7;
      casillas[1][2] = casilla8;
      casillas[1][3] = casilla9;
      casillas[1][4] = casilla10;
      casillas[2][0] = casilla11;
      casillas[2][1] = casilla12;
      casillas[2][2] = casilla13;
      casillas[2][3] = casilla14;
      casillas[2][4] = casilla15;
      casillas[3][0] = casilla16;
      casillas[3][1] = casilla17;
      casillas[3][2] = casilla18;
      casillas[3][3] = casilla19;
      casillas[3][4] = casilla20;
      casillas[4][0] = casilla21;
      casillas[4][1] = casilla22;
      casillas[4][2] = casilla23;
      casillas[4][3] = casilla24;
      casillas[4][4] = casilla25;
    }

    public JLabel[][] getCasillas() {
        return casillas;
    }

    public JButton getBtnReiniciar() {
        return btnReiniciar;
    }

    public JLabel getLblPuntos1() {
        return lblPuntos1;
    }

    public JLabel getLblPuntos2() {
        return lblPuntos2;
    }

    public void setCasillas(JLabel[][] casillas) {
        this.casillas = casillas;
    }

    public JLabel getLblJugador1() {
        return lblJugador1;
    }

    public void setLblJugador1(JLabel lblJugador1) {
        this.lblJugador1 = lblJugador1;
    }

    public JLabel getLblJugador2() {
        return lblJugador2;
    }

    public void setLblJugador2(JLabel lblJugador2) {
        this.lblJugador2 = lblJugador2;
    }
    
    
}
